# Build settings
markdown: kramdown

# Educational history
roles:
 - degree: PhD candidate in Clinical Psychology
   year: 2017-present
   university: The Penn State University
   research: Contextual influences on reward processing in addiction. 
 - degree: M.A. (Psychology)
   year: 2014-2017
   university: San Diego State University
   research: Neural correlates of cognitive and affective functions in binge drinkers.
 - degree: B.S. (Psychology)
   year: 2008-2012
   university: Peking University
   research: The modulating effects of group membership on empathic neural responses.
